# Generated by Django 4.2.6 on 2023-10-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_week', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('cohort', models.CharField(max_length=50)),
                ('results', models.CharField(max_length=500)),
                ('challanges', models.CharField(max_length=500)),
                ('plan', models.CharField(max_length=500)),
            ],
        ),
    ]
