# Generated by Django 4.2.6 on 2023-11-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=2000)),
                ('solved', models.BooleanField(default=False)),
            ],
        ),
    ]
