# Generated by Django 4.2.6 on 2023-10-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportweek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_week', models.CharField(max_length=50)),
            ],
        ),
    ]
